// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"baseframe/internal/goserver"
	"baseframe/internal/goserver/conf"
	user2 "baseframe/internal/goserver/controller/v1/user"
	"baseframe/internal/goserver/data"
	"baseframe/internal/goserver/service/user"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func loadServer(c *conf.Config) *gin.Engine {
	dataData := data.NewData(c)
	userRepo := data.NewUserData(dataData)
	userService := user.NewUserService(userRepo)
	userController := user2.NewUserController(userService)
	engine := goserver.NewHttpServer(userController)
	return engine
}
